name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  frontend-build-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend/react-app

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm test
      - name: Build
        run: npm run build

  backend-build-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend/graphql-server

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm test

  deploy:
    needs: [frontend-build-and-test, backend-build-and-test]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push GraphQL server image to Amazon ECR
        env:
          ECR_REGISTRY: 339712726852.dkr.ecr.us-east-1.amazonaws.com
          ECR_REPOSITORY: graphql
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG ./backend/graphql-server
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Deploy Frontend to S3
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        run: |
          aws s3 sync ./frontend/react-app/build/ s3://$AWS_S3_BUCKET --delete

      - name: Deploy Backend with Serverless Framework
        run: |
          npm install -g serverless
          npm install
          serverless deploy --stage prod

      - name: Update ECS service
        run: |
          aws ecs update-service --cluster your-cluster-name --service your-service-name --force-new-deployment
